### ISSUE TITLE
[1.18.2] Mod crashes

### ISSUE THREAD

**Issue by Raft08** [AbdElAziz333/ForgetMeChunk-Forge#2]
Hello, the modpack crash 
With this error 

`The game crashed whilst unexpected error
Error: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered`

Same modpack as #1 

Here is the log 
[latest.log](https://github.com/AbdElAziz333/ForgetMeChunk-Forge/files/9067269/latest.log)

**Comment by AbdElAziz333** [comment]
it worked in dev i swear, i will try to fix it multiple times.

**Comment by Raft08** [comment]
It's maybe an issue with Rubidium(Sodium fork for Forge) 
I will try to start my modpack without Rubidium

**Comment by AbdElAziz333** [comment]
Please try this update :
https://www.curseforge.com/minecraft/mc-mods/forgetmechunk-forge/files/3866691
This update should makes the mod works good.
